//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrewentoryBackend.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BrewentoryDBEntities1 : DbContext
    {
        public BrewentoryDBEntities1()
            : base("name=BrewentoryDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Inventory> Inventories { get; set; }
        public virtual DbSet<Notetable> Notetables { get; set; }
        public virtual DbSet<Shift> Shifts { get; set; }
        public virtual DbSet<CompletedWork> CompletedWorks { get; set; }
        public virtual DbSet<LiveView> LiveViews { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
        public virtual DbSet<Timesheet> Timesheets { get; set; }
    }
}
