//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrewentoryBackend.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiveView
    {
        public int ProductID { get; set; }
        public string Product { get; set; }
        public string Batch { get; set; }
        public Nullable<int> Pallets { get; set; }
        public Nullable<int> Quantity { get; set; }
        public bool LiveStatus { get; set; }
    }
}
